{% set version = "1.15.0" %}

package:
  name: blosc
  version: {{ version }}

source:
  url: https://github.com/Blosc/c-blosc/archive/v{{ version }}.tar.gz
  sha256: dbbb01f9fedcdf2c2ff73296353a9253f44ce9de89c081cbd8146170dce2ba8f

build:
  number: 1000
  patches:
    - stdint.h.patch  # FIXME remove this once the patch is released from upstream

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -e $PREFIX/include/blosc.h                    # [unix]
    - test -e $PREFIX/include/blosc-export.h             # [unix]
    - test -e $PREFIX/lib/libblosc.a                     # [unix]
    - test -e $PREFIX/lib/libblosc${SHLIB_EXT}           # [unix]
    - if not exist %LIBRARY_INC%\\blosc.h exit 1         # [win]
    - if not exist %LIBRARY_INC%\\blosc-export.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\blosc.dll exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\blosc.lib exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\libblosc.lib exit 1    # [win]

about:
  home: https://github.com/Blosc/c-blosc
  license: BSD 3-Clause
  license_file: LICENSES/BLOSC.txt
  summary: 'A blocking, shuffling and loss-less compression library that can be faster than `memcpy()`'

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
    - jakirkham
    - beckermr
