{% set version = "1.11.3" %}

package:
  name: blosc
  version: {{ version }}

source:
  url: https://github.com/Blosc/c-blosc/archive/v{{ version }}.tar.gz
  sha256: d99605146ae70543130fda78f5644536b6592f482f314ff148924fcb6ef612f4

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - cmake
    - zlib 1.2.*
    - snappy
  run:
    - snappy
    - zlib 1.2.*

test:
  commands:
    - test -e $PREFIX/include/blosc.h                # [unix]
    - test -e $PREFIX/include/blosc-export.h         # [unix]
    - test -e $PREFIX/lib/libblosc.a                 # [unix]
    - test -e $PREFIX/lib/libblosc.dylib             # [osx]
    - test -e $PREFIX/lib/libblosc.so                # [linux]

about:
  home: https://github.com/Blosc/c-blosc
  license: BSD 3-Clause
  license_file: LICENSES/BLOSC.txt
  summary: 'A blocking, shuffling and loss-less compression library that can be faster than `memcpy()`'

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
