appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ttBIejbveKpHdcVI8Vd/HzyOIxK60EF7lhnG63ah0N0m0RXjTKeAhROGUS2IFnTaD6/S5VTYZfmre6x+SpSq69WdhAEFuA47nKrglw52qI7Smb4wJe6F7WJs+E0HNUIQOmYWP4Ig8ny1PKaX//cSB6y5xsWccAvM6mtHIjjo6K002zbLwRC/sSfAzNxbfpIUxUj1U4aGD3ccs7rumVzaDf9RuwiylNge2tnoNtcUlQbqtudOgewx966t2pVmPUpwrcQRw1VsVU9gkrlnbZ2KuhPwZTL16m8TvV+99iJB2DTnJ8nKNc1kWiIJ84RLuyT+SV0a4jwxJBNVGMKENcNEBV3D4fvQT2ywyJw3Rm8rUgzo3jDCF0qUkgDBY2Fxe9OdbPaXMGDkDlJpFzdULG1rjF4NYKcQg9oiDYdJC7IFui/i0sM0wYPNeVrTpLY8Wz239vJOuL7G0+faQcKIki0CC1i2n9U8feytW+GPN8g5YF35F2CJrSr6JD7F+7z+IrY2oRTjLj2i5Nugx6mxjaMa9IbxmN7KElB50AqcpxCe4ehbUTV7SSRpHwWLXxCwRWsmMtraz+1QVxEV4VJOS5+oBm8zwZ1xP8kQfvAbbGXHRT4kzLtx6s2+AmRjmOlGW5sDmu6P1OWNUiBQPCfZvJhA+n7EAW7hmVB3FCC86VHclXI=}
